### ISSUE TITLE
文書リソースのセクション追加

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/www.mozilla.jp#3]
コミュニティにとって重要な文書を公開するページを追加したいです。
具体的には以下のものです。

1. [現在翻訳レビュー中の MPL 2.0 日本語訳](https://github.com/mozilla-japan/translation/issues/502) のコンテンツ
2. [コミュニティ参加ガイドライン](https://www.mozilla.org/ja/about/governance/policies/participation/) へのリンク
3. [各ガイドライン等を含む mozilla-japan / translation の Wiki ページ](https://github.com/mozilla-japan/translation/wiki) へのリンク

**Comment by marsf** [comment]
構成案：

- トップページの「Mozilla 関連コミュニティ紹介」と「その他 Mozilla 関連リンク」の間に「コミュニティ関連文書」のセクションを追加して上記の項目を含める。
- MPL 2.0 日本語訳は「/content/documents」のディレクトリーを追加して、その中にコンテンツを配置する。

**Comment by marsf** [comment]
コンテンツ案：

- MPL 2.0 日本語訳
  - Mozilla が策定したライセンス「Mozilla Public License version 2.0」の Mozilla Japan コミュニティによる日本語参考訳です。Mozilla 製品のソースコードに適用されています。
- Mozilla コミュニティ参加ガイドライン
  - Mozilla コミュニティに参加するにあたり、すべての参加者に守ってほしいガイドラインです。
- Mozilla 翻訳＆ローカライズコミュニティ Wiki
  - ドキュメント翻訳の始め方や表記ガイドライン、各ウェブサイトへのリンクが含まれます。

**Comment by Guest126** [comment]
>     * MPL 2.0 日本語訳は「/content/documents」のディレクトリーを追加して、その中にコンテンツを配置する。

MPL 2.0はライセンス本文だけでなく、[MPLの概要](https://www.mozilla.org/en-US/MPL/)や[MPL 2.0 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)の翻訳も見込まれるので、mozilla.orgのディレクトリ構造から「/MPL」以下をそのまま拝借するのはどうですか。

**Comment by marsf** [comment]
PR https://github.com/mozilla-japan/www.mozilla.jp/pull/4 でコミットしました。

> MPL 2.0はライセンス本文だけでなく、MPLの概要やMPL 2.0 FAQの翻訳も見込まれるので、mozilla.orgのディレクトリ構造から「/MPL」以下をそのまま拝借するのはどうですか。

MPL 2.0 本文は /documents/mpl/2.0/  に配置。ついでに MPL 1.1J も元の HTML をそのままコピーして /documents/mpl/MPL-1.1J.html に置きました。
Hugo の制限なのか、大文字のディレクトリー名が使えず「/MPL」でページが表示できませんでした。

この issue はコミュニティ関連文書のセクションを追加するだけなので、MPL 2.0 文書の追加と更新は別 issue で扱いたいと思います。

**Comment by marsf** [comment]
コミットをマージしました。すぐにサイトに反映されるんですね。

MPL 2.0 日本語訳ページへのリンクは「準備中」としています。
リポジトリーにファイルを置いているので、次の issue でレビュー更新を反映させていきます。
