### ISSUE TITLE
MPL 2.0 の日本語訳のライセンスについて

### ISSUE THREAD

**Issue by Guest126** [mozilla-japan/www.mozilla.jp#8]
すでに #5 でMPL 2.0 の日本語訳が公開された後で恐縮なのですが、実は昨年それについて Mozilla とメールでやり取りした話があるので、ここに書き残します。

まず大前提として、mozilla.org のコンテンツはクリエイティブ・コモンズ (CC BY-SA 3.0) のライセンスの下で公開されています。

- [Mozilla.orgサイトライセンスポリシー](https://www.mozilla.org/en-US/foundation/licensing/website-content/)

すると、mozilla.org のドメイン下で公開されている MPL 2.0 も CC BY-SA 3.0 に基づいて公開されており、その日本語訳の公開にあたってはライセンスの継承が必要ということになります。

しかし、一般的に（少なくとも日本法においては）原則として契約書の類に著作権は認められていません。著作物でないものに CC ライセンスを適用することはできません。仮に適用できたとして、法的強制力はありません。

この点について、Mozilla Foundation に問い合わせをしたのですが、何度かのやり取りを経て、調査中との返事を最後に、返信が途絶えてしまいました。メールの内容は次の通りです。

> From: Guest126
> To: mhoye, licensing@mozilla.com
> Sent: 2021-02-07 22:58
>
> I'm still expecting your response regarding the below.
> 
> Best regards,
> 
> > From: mhoye
> > To: Guest126
> > Sent: 2020-12-17 00:07
> > 
> > Pardon me, I'm still investigating the question of whether an unofficial
> > translation of a licensed document require relicensing under similar
> > terms.
> > 
> > -   mhoye
> >     
> > > From: Guest126
> > > To: mhoye, licensing@mozilla.com
> > > Sent: 2020-12-16 5:17
> > >
> > > I would like to remind you that I still have not received your response about the below email.
> > > 
> > > > From: Guest126
> > > > To: mhoye
> > > > Sent: 2020-12-08 12:27
> > > > 
> > > > Thank you for your answer.
> > > > 
> > > > I'd like to confirm, is the MPL text published under CC BY SA 3.0?
> > > > Do I have to share alike under CC BY SA 3.0 to redistribute MPL and its translations?
> > > > 
> > > > > From: mhoye
> > > > > To: Guest126
> > > > > Sent: 2020-12-08 5:56
> > > > > 
> > > > > You're certainly welcome to make a Japanese translation, but please make a note that it is your own work, an unofficial translation not endorsed by or reviewed by Mozilla. Unfortunately, we cannot endorse or "bless" translations of the MPL, and only the English version can be the official version.
> > > > > 
> > > > > -   mhoye
> > > > > 
> > > > > > From: Guest126
> > > > > > To: licensing@mozilla.org
> > > > > > Sent: 2020-12-06 5:35
> > > > > > Subject: [Licensing] Can I translate the MPL?
> > > > > > 
> > > > > > I’m working on MPL 2.0 Japanese translation.
> > > > > > Please let me know any translations guidelines what I should be follow,
> > > > > > like GNU GPL (https://www.gnu.org/licenses/translations.en.html).
> > > > > > For example, I think it should be declared that it is an unofficial and not a legally valid.
> > > > > > By the way, can it be adopted as an official translation?
> > > > > > Related question: Is the MPL license texts a copyrighted work?
> > > > > > The text of documents on the Mozilla.org site is available under the CC BY SA 3.0.
> > > > > > https://www.mozilla.org/en-US/foundation/licensing/website-content/
> > > > > > However, in general, the license test is not copyrighted (at least in Japan, maybe also in US).
> > > > > > So I think I'm free to translate it or distribute include it in the software source, without following the CC license terms, is that correct?

（メールヘッダはプライバシーのため一部加工、本文は原文ママ）

私の方でやれるだけのことはしたので、あとはコミュニティの方々に委ねたいと考えています。

**Comment by hmatrjp** [comment]
共有ありがとうございます。

日本のコミュニティーとしては、MPL原文の解釈の助けになればと思って公開するもの、という位置づけ（ですよね？）ということと、
下記と合わせて注釈しておくのが手かと思います。

・日本では、契約書の類には著作権が一般的には認められない、また、CC は、著作権のないものには適用できないが、Mozillaは、MPL2.0の原文を、CC-BY-SA 3.0 で公開している
・Mozilla としては、翻訳を歓迎するものの、公式のものとしてお墨付きを与えることはできず、CC-BY-SA を適用するべきかの結論を出していない（結論が出てきたときには、訳の取り扱いが変わる可能性がある？）

GPLとかの訳も、理解の参考として、という注釈をよく見るように思いますが、似たような事情ではないでしょうか（推測）。

**Comment by Guest126** [comment]
注釈は翻訳文を読んだ人の理解を促したり、誤解を抱かれないようにするためのものであって、著作権上の解釈問題を回避できるとまでは考えていません。例えば日本の漫画を海外のファンが無断で翻訳して公開することは「解釈の助けになれば」という想いであったとしても許されない海賊行為です。メールでは注釈と著作権について関連する事項として問い合わせていますが、別個の問題として捉えた方が良いでしょう。

日本語での翻訳を歓迎するという mhoye 氏の言質を取れたので Mozilla から怒られることはないと思いますが、mozilla.jp で公開している日本語訳のライセンスが不明（プロプライエタリ？）なので、コピーサイト対策としてわざとそうしているのか、単に失念しているだけなのかは確認しておきたいところです。

ちなみに、MJ 訳の元となった note 訳は念のために [CC0](https://creativecommons.org/publicdomain/zero/1.0/deed.ja) ライセンスを宣言し、パブリックドメインにしてあります。私が明日死んで諸々の権利が遺族や債権者に渡ったとしても訳文の著作権を主張することはできません。

**Comment by hmatrjp** [comment]
mozilla.jp で公開している日本語訳のライセンスについては、事情をご存知の方に譲るとして、他の点についてです。

mhoyeさんと Guest126さんの一連のメールを読み返してみると、mhoyeさんから
> please make a note that it is your own work,

とあるので、訳は訳した人の著作物として扱ってくれ、という意図のように思います。

もし、この解釈が正しければ、CC-BY-SAとして扱わなければいけない、という前提は崩れますし、ライセンスを設定しないという選択肢を含めて、訳した人が勝手にどのライセンスを使うか決めれば良いことになりませんか？

どのような場合にCC-BY-SAとして扱わなければいけないのか、という疑問は出てきますが、今話題になっている問題の外の話ですので、とりあえず措きます。（英語で改変して流用するときの話なんだろうな、という予想ができるのみ）。

note訳についてのCC0ライセンス、お気遣いありがとうございます。

**Comment by marsf** [comment]
おそらくですが、mozilla.org サイトの MPL 2.0 に著作権が認められないということについて、CC-BY-SA による著作権がライセンスの文言内容ではなく、少なくともページのマークアップと CSS スタイルそのものに対しては適用されている、という解釈もできるのではないでしょうか。

翻訳して公開することについては、CC ライセンスにより認められています。
- https://creativecommons.org/licenses/by-sa/3.0/deed.ja
- https://creativecommons.org/faq/#do-creative-commons-licenses-affect-exceptions-and-limitations-to-copyright-such-as-fair-dealing-and-fair-use

ただし CC-BY-SA では、
1. 適切なクレジットを表示し、
2. 原文へのリンクを提供し、
3. 原文と同じライセンスを適用する

必要があります。

1 についてはライセンス名そのものが表している、といえないでしょうか。 また、非公式であり法的に有効でないことも明記してあります。
2 はリンクを提供しているのでクリアしています。 
3 をどのように表示するか、という部分が検討すべき問題になると思います。

> mozilla.jp で公開している日本語訳のライセンスが不明（プロプライエタリ？）なので、コピーサイト対策としてわざとそうしているのか、単に失念しているだけなのかは確認しておきたいところです。

原文の CC ライセンスにより、その日本語訳文 (mozilla.jp のページそのものではなく翻訳テキスト部分) をプロプライエタリとしてライセンスすることは認められていません。そもそも ShareAlike なのでコピー自由です。

**Comment by marsf** [comment]
参考： 可知さんのブログ記事

エンジニアのための契約勉強会 – オープンソースライセンス編まとめ
https://www.catch.jp/oss-license/2015/06/27/seminar/

**Comment by Guest126** [comment]
> mhoyeさんと Guest126さんの一連のメールを読み返してみると、mhoyeさんから
> 
> > please make a note that it is your own work,
> 
> とあるので、訳は訳した人の著作物として扱ってくれ、という意図のように思います。

MPL 2.0 の原文をパブリックドメインとして扱うにしろ、CC-BY-SA として扱わなければいけないにしろ、日本やアメリカなどのベルヌ条約加盟国では翻訳をした人に二次著作物としての著作権が自動的に発生するという当然の事実を述べたに過ぎませんから、この一文から

> もし、この解釈が正しければ、CC-BY-SAとして扱わなければいけない、という前提は崩れますし、ライセンスを設定しないという選択肢を含めて、訳した人が勝手にどのライセンスを使うか決めれば良いことになりませんか？

と判断することは早計だと思います。その点を明確にするため、mhoye 氏に質問を重ねたところ、言葉を濁されたところがますます怪しいです。

**Comment by Guest126** [comment]
> おそらくですが、mozilla.org サイトの MPL 2.0 に著作権が認められないということについて、CC-BY-SA による著作権がライセンスの文言内容ではなく、少なくともページのマークアップと CSS スタイルそのものに対しては適用されている、という解釈もできるのではないでしょうか。

そういう解釈も可能だとは思いますが、結局は想像の域を出ないので、何らかの裏付けが欲しいところです。多分ここで議論しても結論は出ないので、伝手でも何でも使って誰かが Mozilla に確認するしかないと思っています。正規ルートで問い合わせて私は玉砕しましたが、別の方であればちゃんとした答えが返ってくるかもしれません。

それと並行して為念的に MPL 2.0 日本語訳を CC BY-SA でライセンスすることを検討するのが良さそうですね。これを決めておかないと MPL 2.0 日本語訳を他のメンバーが弄るのにいちいち私と marsf 氏の許諾が必要になってしまいます。

> 1 についてはライセンス名そのものが表している、といえないでしょうか。 また、非公式であり法的に有効でないことも明記してあります。 2 はリンクを提供しているのでクリアしています。 3 をどのように表示するか、という部分が検討すべき問題になると思います。

1 をライセンス名から類推させるのは少し無理がある気がします（そもそも Mozilla Foundation の方なのか Mozilla Corporation の方なのか分かりません）が、第10.1節で「Mozilla Foundation がライセンス管理者です。」と書いてあることで準拠しているとみなして良いのではないかと思います。

3 は本家 Mozilla を真似てサイトフッターに表示するのも一つの手だと思います。表示する階層によっては他のコンテンツも巻き添えを食らいますが、GitHub で共同管理するなら丁度いいのではないでしょうか。

**Comment by hmatrjp** [comment]
> もし、この解釈が正しければ、CC-BY-SAとして扱わなければいけない、という前提は崩れますし、

ここの部分、（訳には訳で当然、原文とは別途著作権が発生するものだから、CC-BY-SAが継承される条件はそれを前提として書かれているはずで）私の理解が間違っていました。すみませんでした。

以下、思いつきレベルですが、後で自分でも見直せるように書いておきます。

・別ルートでの確認：
　・ぱっと思いつくのは、discourse です。　https://discourse.mozilla.org
　　MPLそのものを扱うカテゴリは見つけられておらず、新たにカテゴリを起こす必要があるかもしれません。
　・答えをもらうための聞き方にひと工夫いるかもしれません。　CC-BY-SAを適用しなければいけないのか、と尋ねるのではなく、
　　・訳を公式のものとして認めないなら、MPL原文自体を（mozilla.org の配下にあるが）CC-BY-SAの適用外としてもらえないか etc.

・MPL2.0日本語訳を CC-BY-SAでライセンスするために：
　MPLの日本語を、契約書の類 とみなすと、日本の著作権法では著作権の保護対象とならず、CC-BY-SA の適用対象外となってしまうが、契約書の類 でないとみなせば（みなせるように、なにか解説文を追加するとか？）、著作権の保護対象になり、CC-BA-SAの保護対象になるかも。

**Comment by marsf** [comment]
> 訳を公式のものとして認めないなら、MPL原文自体を（mozilla.org の配下にあるが）CC-BY-SAの適用外としてもらえないか etc.

翻訳に関わった者として、法的効力を持たせるだけの責任を負えないという意味で、**この (Mozilla Japan コミュニティの) 日本語参考訳を**公式のものとして認めてもらうことも正式な許諾書とすることも、しなくてよいと考えています。それに、mhoye さんからは、翻訳版を公式にすることはできないという回答です。（11/14括弧を追記）
もし法的に有効な日本語訳が必要であれば、別途、法律の専門家に依頼して文書を改訂してもらべきだし、Mozilla との交渉も必要になります。 

とすると問題は、原文が著作権保護の対象になるかどうかとは関係なく、この日本語参考訳を著作権的にどう扱い表示するかということです。

最初に戻って Guest126 さんの質問の回答待ちですが、原文 (サイト) の CC-BY-SA に従うべきであれば、同じ CC-BY-SA もしくは [CC-BY-SA と互換性のあるライセンス](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses)にしなければなりません。
そうでない場合でも、翻訳者が日本語参考訳の原著作権者になるので、CC-BY-SA にすることはできると思います。

- [【CCPLv3.0】著作者人格権（同一性保持権）に関する議論](https://creativecommons.jp/2006/11/15/ccplv3-discussion/)
- [【解説】 クリエイティブ・コモンズ・ライセンス入門 【知財管理65巻6号掲載】](https://masudalaw.wordpress.com/2016/05/06/ccl-basics/)

CC-BY-SA 4.0 にするのもアリだと思います。

**Comment by marsf** [comment]
> 翻訳に関わった者として、法的効力を持たせるだけの責任を負えないという意味で、この日本語参考訳を公式のものとして認めてもらうことも正式な許諾書とすることも、しなくてよいと考えています。

ただし、この日本語参考訳を mozilla.jp ドメイン下に置き、Mozilla Japan コミュニティ訳としたのは、できる限りのこととして、それなりの意図があってのものです。

**Comment by hmatrjp** [comment]
和訳を契約書の類とみなさなければ、CC-BY-SAを適用して公開できる、というところまでは、 @marsf さんも @Guest126 さんも同じ解釈ではないかと思います。

かつ、原文が CC-BY-SAとして公開されているので、和訳も CC-BY-SAと互換性のあるライセンスで公開するべきだというのが、2つ前の [marsfさんのコメント](https://github.com/mozilla-japan/www.mozilla.jp/issues/8#issuecomment-967008549)。

このMPLの場合、契約書文面の訳が、契約書の類ではない、ということで見解が統一できれば、
Mozillaの意向を改めて確認するまでもなく、
CC-BY-SAで和訳を公開すれば良いように思いますが、拙速でしょうか？ 
それとも、[Guest126さんの最初のコメント](https://github.com/mozilla-japan/www.mozilla.jp/issues/8#issue-1049123020)と真っ向からぶつかってしまうでしょうか？

**Comment by marsf** [comment]
> かつ、原文が CC-BY-SAとして公開されているので、

本当に原文に CC-BY-SA が適用されているのか、が Mozilla に確認しなければならないところです。
法的拘束力があってもなくても CC-BY-SA 3.0 (or later) でライセンスする分には何の問題もないと思いますが。

　
> そうでない場合でも、翻訳者が日本語参考訳の原著作権者になるので、CC-BY-SA にすることはできると思います。

これは、[ベルヌ条約 第2条(3)](https://www.cric.or.jp/db/treaty/t1_index.html) によります。
> (3) 文学的又は美術的著作物の翻訳、翻案、編曲等による改作物は、その原作物の著作者の権利を害することなく、原著作物として保護される。

**Comment by marsf** [comment]
> 3 は本家 Mozilla を真似てサイトフッターに表示するのも一つの手だと思います。表示する階層によっては他のコンテンツも巻き添えを食らいますが、GitHub で共同管理するなら丁度いいのではないでしょうか。

mozilla.jp のコンテンツと呼べるものは、「[法人向け情報](https://www.mozilla.jp/business/)」と「[関連文書](https://www.mozilla.jp/documents/) (MPL)」だけです。

法人向け情報については、@piroor さんに確認が取れればよいでしょう。
https://github.com/mozilla-japan/www.mozilla.jp/tree/main/content/business

すでに終了している [modest (dev.mozilla.jp) は CC-BY-SA 3.0 でライセンスされています](https://dev.mozilla.jp/about/license/)。

**Comment by piroor** [comment]
個人的には、文を提供した時点で後の事（ライセンス変更ほか）は全部プロジェクトの判断に委ねた扱いでいいと思っていますが、社としてのコントリビュートでもあるので、一応会社の方に聞いてみようと思います。週明けまでお待ち頂けましたら幸いです。

**Comment by piroor** [comment]
確認が取れました。自分の提供した部分はCC-BY-SA 3.0に統一する対象に含めて頂いて大丈夫です！

**Comment by hmatrjp** [comment]
Discourse に関連する質問を投稿しました。
https://discourse.mozilla.org/t/mpl-2-0-itself-is-licensed-under-cc-by-sa/88958
MPL 2.0 そのものは CC-BY-SA でライセンスされているのか、と問う内容です。
不十分でしたら、補足いだたけると幸いです。

**Comment by hmatrjp** [comment]
discourse での説明ありがとうございました。 @marsf 

Daniel Nazer氏 （私は面識がないのですが、IP & Product Counsel at Mozilla legalとあり、検索結果のLinkedIn 等でもそのように出てきます。）　から回答があり、MPL 2.0の原文を、CCでライセンスされているものとみなす必要はない、とのことです。
https://discourse.mozilla.org/t/mpl-2-0-itself-is-licensed-under-cc-by-sa/88958/4

同じく Daniel さんからは、和訳は法的に有効でない・・・を、英語でも書いておいたらどうかということで、文もいただいています。

> “This is a community translation of the Mozilla Public License 2.0. that is provided for reference. But please note that only the original English version is the official Mozilla Public License 2.0.”

mozilla.jp での掲載を、日本語が読める人のみを対象とするのであれば、英語での記載は必要ない気もしますが。

**Comment by marsf** [comment]
ライセンスに関しては解決しましたね。あとはこちらで自由にライセンスを適用することができます。

> mozilla.jp での掲載を、日本語が読める人のみを対象とするのであれば、英語での記載は必要ない気もしますが。

公開されている以上、対象を選ぶことはできません。よく分からずに日本語訳の「別記 A、B」を使われても問題になると思います。

ここは大事を取って、いただいた英語の注記と「本参考訳の別記 A および B を対象ソフトウェアに用いることはできません」の注意書きを加えたほうが良いと思います。

**Comment by hmatrjp** [comment]
> ここは大事を取って、いただいた英語の注記と「本参考訳の別記 A および B を対象ソフトウェアに用いることはできません」の注意書きを加えたほうが良いと思います。

賛成します。

**Comment by marsf** [comment]
Netlify 側のアカウントの問題で、Github 上の変更が公開ページに反映されていないようです。
https://github.com/mozilla-japan/www.mozilla.jp/runs/10026835132

この issue そのものは解決したので close します。

**Comment by marsf** [comment]
変更が反映されました。
